spring:
  application:
    name: command-service
  main:
    web-application-type: none
  datasource:
    url: jdbc:postgresql://localhost:5433/cqrs2
    username: cqrs2
    password: cqrs2
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      mode: always
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
